# Change these first
owner: Sternwarte-St-Ottilien-e-V # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees: # Users to assign downtime issues (optional)
  - leitmori

sites:
  - name: Website
    url: https://sternwarte-ottilien.de
  - name: Rocket.Chat
    url: $CHAT
  - name: Nextcloud
    url: $NEXTCLOUD
    maxRedirects: 10
  - name: AllSky
    url: $ALLSKY
  - name: Wetter
    url: $WETTER
  - name: Inventarverwaltung
    url: $INVENTAR
  - name: Vereinsverwaltung
    url: $VEREIN
  - name: Tickets
    url: $TICKETS
  - name: Wiki
    url: $WIKI
  - name: Newsletter
    url: $NEWSLETTER
  - name: Webmail
    url: $WEBMAIL
  - name: SMTP
    check: "tcp-ping"
    url: $SMTP
    port: 25
  - name: DNS (Primary Master)
    check: "tcp-ping"
    url: $PRIMARY_NS
    port: 53
  - name: DNS (he.net)
    check: "tcp-ping"
    url: $HE_NS
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sternwarte-ottilien.de
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Sternwarte-St-Ottilien-e-V/status/master/assets/logo.svg
  favicon: https://raw.githubusercontent.com/Sternwarte-St-Ottilien-e-V/status/master/assets/favicon.png
  faviconSvg: https://raw.githubusercontent.com/Sternwarte-St-Ottilien-e-V/status/master/assets/logo.svg
  metaTags:
    - name: "robots"
      content: "noindex"
  name: Sternwarte St. Ottilien
  navbar:
    - title: Links
      href: https://sternwarte.space

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
